"""V2 基础设施默认值。"""

DEFAULT_EVENT_BUS_CAPACITY = 10_000
DEFAULT_EVENT_SCHEMA_VERSION = 1
DEFAULT_RULESET_REVISION = "phase14-overnight-priority-shadow"
DEFAULT_STRATEGY_NAME = "capital-flow-v2"
DEFAULT_WRITE_TIMEOUT_SECONDS = 15.0
DEFAULT_NOTIFICATION_EXPIRY_SECONDS = 300
DEFAULT_NOTIFICATION_MAX_ATTEMPTS = 3
EXECUTION_CONFIRMATION_TOKEN = "I_ACKNOWLEDGE_V2_REAL_TRADING"
